### ISSUE TITLE
HOME not set when only "user" is specified

### ISSUE THREAD

**Issue by axinojolais** [canonical/pebble#183]
Using pebble on a charm deployed on a 2.9.32 juju controller

My app was misbehaving because HOME wasn't set to /home/foo even though I specified `user: "foo"` in the pebble plan. I found https://github.com/canonical/pebble/pull/129 which sets HOME if both `user` and `group` are set, but I would expect HOME to be set as soon as just `user` is set.

I don't have a reason to not set `group`, I just don't really care about the group (and I would also assume that just setting the user would also set the group to the user's GID for me).

Anyway, I can work around the issue by setting HOME explicitly (my juju version is too old to have #129), but it would be nice if pebble could do that for me.

Thanks !

**Comment by benhoyt** [comment]
Thanks for this. We can dig in deeper, but at first glance it makes sense to set HOME when only user is specified.

For the record, yes, Juju 2.9.32 is on Pebble commit 32ead042e947, which doesn't include the change you referenced (or things like https://github.com/canonical/pebble/pull/114). The latest 2.9.x version (.39 I think) does. But as you point out, you'd still have to set user and group.

**Comment by benhoyt** [comment]
Per discussion on #521, we can't actually see how this can happen looking at the code now, because of how `osutil.NormalizeUidGid` looks up the gid if group is not set (and, at the bottom of the function, returns an error if the plan didn't specify both user and group).

If this happens again or you can find a reproducer, feel free to reopen (or open a new issue).
