### ISSUE TITLE
Document ChangeError is raised even while setting the layer as "on-failure: ignore"

### ISSUE THREAD

**Issue by amandahla** [canonical/pebble#377]
Could this be added as a note to the https://github.com/canonical/pebble?tab=readme-ov-file#layer-specification , please?

If wasn't [this](https://github.com/canonical/pebble/issues/240) issue and this [comment](https://github.com/canonical/pebble/issues/240#issuecomment-1599722443) I wouldn't figured out this behavior.

Thanks.

**Comment by benhoyt** [comment]
Hi @amandahla, thanks for the report. Is this happening because the service you're trying to start is exiting in less than 1 second? That is documented in the "Using Pebble" part of the README:

> When starting a service, Pebble executes the service's command, and waits 1 second to ensure the command doesn't exit too quickly. Assuming the command doesn't exit within that time window, the start is considered successful, otherwise pebble start will exit with an error.

However, I acknowledge we may want to say something explicit about how this still applies even when `on-failure: ignore` is set.
