### ISSUE TITLE
Pebble should let the container crash when a service fails to auto-start

### ISSUE THREAD

**Issue by mmanciop** [canonical/pebble#41]
If Pebble has one or more pre-defined services to _automatically run_ inside a container (as opposed to being started by a Juju sidecar), by default it should make the container crash if any of them fails to start. This behavior would be in line with Docker's `ENTRYPOINT`, and Pebble not letting containers crash play poorly on Kubernetes hiding crash loops and associated K8S events; accustomed as I am to Docker or K8S, the current behavior of Pebble seems to leave by default containers in a zombie state and invalidate key operational aspects of K8S pods and `kubectl`.

Additionally, it may be desirable to have `optional` services, explicitly flagged as such (which would be more or less the equivalent of optional containers in an ECS task), with the current behavior that Pebble is using for services.

**Comment by benhoyt** [comment]
@mmanciop Thanks for the bug report. I want to make sure I understand: are we talking about this in the context of Juju sidecar charms? I realize you say "as opposed to being started by a Juju sidecar", but in that case I'm not quite sure what the context is.

Juju starts Pebble with `pebble run --hold`, and the `--hold` argument means "don't start services automatically". The idea is to give the charm control over when to call `autostart()` or `start('svc')`. So even if we made Pebble exit with an error if one of the autostart services failed to start, it wouldn't execute this code path in the context of Juju, due to `--hold`.

**Comment by mmanciop** [comment]
Hi, yes, it was in the context of sidecar charms. Coming from the K8S world, I find the behavior of pebble very much surprising. But I under Now better the rationale of pebble and services, so we can close this bug.
