### ISSUE TITLE
config-changed hook is triggered before pebble ready

### ISSUE THREAD

**Issue by guoqiao** [canonical/pebble#52]
If pebble is not ready, charm container can not talk to app container, nothing could the charm do.
It seems make no sense to trigger config-changed or any hook before on_pebble_ready event.

However,I noticed when I run juju deploy or juju upgrade-charm, config-changed hook will be triggered
before pebble ready more than once. Here is the log in my [pihole charm](https://github.com/guoqiao/charm-k8s-pihole):

```
...
unit-pihole-0: 22:29:33 INFO unit.pihole/0.juju-log Running legacy hooks/start.
unit-pihole-0: 22:29:33 WARNING unit.pihole/0.juju-log config-changed hook triggered while pebble is not ready, defer event
unit-pihole-0: 22:29:33 INFO juju.worker.uniter.operation ran "start" hook (via hook dispatching script: dispatch)
unit-pihole-0: 22:29:36 WARNING unit.pihole/0.juju-log config-changed hook triggered while pebble is not ready, defer event
unit-pihole-0: 22:29:36 INFO unit.pihole/0.juju-log on_pihole_pebble_ready triggered
...
```

At first, I keep getting pebble errors in config-changed hook, until I realized the fact that pebble could be not ready.
I can see these logs now because I checked the exception and handled it.
This also implies, in the config-changed hook, every charm will need to repeat the code of checking pebble connection, catch ops.pebble.ConnectionError,  and defer event.

What I expect:

if pebble is not ready, no hook should be triggered.

**Comment by jnsgruk** [comment]
This is expected behaviour -- all charms trigger the `config-changed` event immediately after the `start` event, including those that rely upon Pebble.

The `<container>-pebble-ready` event will occur some arbitrary time *after* the charm is deployed, and in fact can occur multiple times. The event is fired in response to the container being scheduled, started and the Pebble API becoming available to the charm code. It could fire again if the workload container were to die and be recreated.

We are working on an addition to the Operator Framework which will allow you to more simply check if pebble is indeed ready in your `config-changed` handler, without relying on trapping the `ops.pebble.ConnectionError`, but for now that is the safest route :)

**Comment by rbarry82** [comment]
See [this](https://github.com/canonical/operator/issues/553) also. We'll provide a way to check in the operator framework.

**Comment by guoqiao** [comment]
@rbarry82   thanks,  as working is already in progress in other issues, I will close this one.
