### ISSUE TITLE
juju unit IP will change on each charm upgrade

### ISSUE THREAD

**Issue by guoqiao** [canonical/pebble#53]
How to reproduce:

1) deploy any k8s charm to a microk8s juju env, you will see unit IP in juju status
2) run a charm upgrade: juju upgrade-charm --path ./$APP.charm $APP
3) when juju settle, you will noticed unit IP changed.

I understand the juju unit in k8s env is a pod, and this makes sense in k8s context.
However, in juju context, for classic juju unit/charm, IP won't change in charm upgrade.

I am not sure this is a bug or not, raise the issue for discussion.

**Comment by jnsgruk** [comment]
This isn't a bug, this is indeed a function of how workloads are scheduled by Kubernetes. When you upgrade the charm, each pod is rescheduled but will retain its identity within the cluster (because currently workloads using Pebble are deployed as `StatefulSet`s).

There is an ongoing discussion about how we might enable the *charm code* to be upgraded independently of the workload, which will likely be able to achieve without pod churn. Any upgrade to a charm that *requires* a new container to be created in the pod (such as changing the version of the workload container) will always result in the pod being recreated.

As for non-Kubernetes charms using Pebble, as far as I know there aren't any of those yet, but in any case there is no reason why such a charm would receive a new IP as the `upgrade-charm` mechanism would still be interacting with the underlying LXD/VM/whatever in the same way it always has :) 

Hope this helps :)

**Comment by guoqiao** [comment]
@jnsgruk  thanks.
